//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba2V19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosClock
    {
        public int IdPos { get; set; }
        public int IdMarka { get; set; }
        public int IdType { get; set; }
    
        public virtual MarkaClock MarkaClock { get; set; }
        public virtual TypeClock TypeClock { get; set; }
    }
}
